#!/bin/bash
# USAGE: command multimedia spotify
# NOTE: wget GPG-KEY from slackbuilds.org then gpg --import to pass "Successfully checked"
# /usr/local/src has g+rw and root:user
set -e
PACK=$1
OUTPUT=/usr/local/etc
export OUTPUT
cd /usr/local/src/$PACK
# build
./$PACK.SlackBuild
cd $OUTPUT
FILENAME=`ls $PACK*.tgz | head -1`
echo "Run installpkg $FILENAME"
